import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/read/afribox-api",
    },
    {
      type: "category",
      label: "core",
      link: {
        type: "doc",
        id: "api/read/core",
      },
      items: [
        {
          type: "doc",
          id: "api/read/post-core-billingtypes-list",
          label: "Billingtypes List",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-boxes-availability",
          label: "Boxes Availability",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-boxes-available-bycity",
          label: "List available boxes by city",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-boxes-available-bystate",
          label: "List available boxes by state",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-boxes-available-list",
          label: "List boxes with a free locker",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-boxes-bycity",
          label: "List boxes by city",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-boxes-bystate",
          label: "List boxes by state",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-boxes-info",
          label: "Get boxes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-boxes-list",
          label: "List the boxes of the network",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-cities-bystate",
          label: "Cities Bystate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-cities-info",
          label: "Cities Info",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-cities-list",
          label: "Cities List",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-couriers-list",
          label: "Couriers List",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-deliveryareas-list",
          label: "Deliveryareas List",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-fees-appless",
          label: "Fees Appless",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-fees-compute",
          label: "Fees Compute",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-fees-selfstorage",
          label: "Fees Selfstorage",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-fees-service",
          label: "Fees Service",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-lockerstatuses-list",
          label: "List the locker statuses",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-parcels-search",
          label: "Parcels Search",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-parcelstatuses-list",
          label: "List parcelstatuses",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-requesttypes-list",
          label: "List the request types",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-sizes-fees",
          label: "Sizes Fees",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-sizes-info",
          label: "Sizes Info",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-sizes-list",
          label: "Sizes List",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-states-info",
          label: "States Info",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-states-list",
          label: "List states",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-core-walletfundmodes-list",
          label: "Walletfundmodes List",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "customer",
      link: {
        type: "doc",
        id: "api/read/customer",
      },
      items: [
        {
          type: "doc",
          id: "api/read/post-customer-cards-info",
          label: "Cards Info",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-customer-cards-list",
          label: "List the customer's saved cards",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-customer-dashboard",
          label: "Customer Dashboard",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-customer-info",
          label: "Customer Info",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-customer-parcels-all",
          label: "List all customer parcels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-customer-parcels-archived",
          label: "List archived parcels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-customer-parcels-cancelled",
          label: "List the customer's cancelled parcels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-customer-parcels-delivered",
          label: "List delivered parcels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-customer-parcels-enroutetorecipient",
          label: "List parcels enroute to the recipient",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-customer-parcels-info-all",
          label: "Get one customer parcel with its timeline",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-customer-parcels-info",
          label: "Get one customer parcel",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-customer-parcels-inlocker",
          label: "List parcels in a locker",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-customer-parcels-newrequests",
          label: "List the customer's new parcel requests",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-customer-parcels-reports",
          label: "Report the customer's parcels in a date range",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-customer-parcels-timeline",
          label: "Customer: Parcels Timeline",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "business",
      link: {
        type: "doc",
        id: "api/read/business",
      },
      items: [
        {
          type: "doc",
          id: "api/read/post-business-availableboxes-all",
          label: "List the business's boxes with a free locker",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-availableboxes-city",
          label: "List the business's available boxes by city",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-availableboxes-state",
          label: "List the business's available boxes by state",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-balance",
          label: "Get the balance business",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-boxes-all",
          label: "List all boxes of the business",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-boxes-assigned",
          label: "List the boxes assigned to the business",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-boxes-city",
          label: "List the business's boxes by city",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-boxes-info",
          label: "Boxes Info",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-boxes-state",
          label: "List the business's boxes by state",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-cancelledparcels",
          label: "List the business's cancelled parcels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-cities-all",
          label: "List the cities of the business network",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-cities-state",
          label: "Cities State",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-dashboard",
          label: "Business Dashboard",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-draft-deliveryareas",
          label: "Draft Deliveryareas",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-draft-parceltypes",
          label: "Draft Parceltypes",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-parcels-info-all",
          label: "Info All",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-parcels-info",
          label: "Parcels Info",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-parcels-reports",
          label: "Parcels Reports",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-parcels-search",
          label: "Find a business parcel by reference",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-parcels-snapshots",
          label: "List a business parcel's snapshots",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-parcels-timeline",
          label: "Business: Parcels Timeline",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-pendingdropoffs",
          label: "List parcels awaiting drop-off",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-pendingpickups",
          label: "List parcels awaiting collection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-pickedupparcels",
          label: "Business Pickedupparcels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-retrievedparcels",
          label: "List the business's retrieved parcels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-sizes",
          label: "Business Sizes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-states",
          label: "List the states of the business network",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-transactionhistory",
          label: "Business Transactionhistory",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-business-users-list",
          label: "List the business's staff users",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "pay",
      link: {
        type: "doc",
        id: "api/read/pay",
      },
      items: [
        {
          type: "doc",
          id: "api/read/post-pay-search",
          label: "Find a parcel for payment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read/post-pay-status",
          label: "Get payment status by reference",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "parcel",
      link: {
        type: "doc",
        id: "api/read/parcel",
      },
      items: [
        {
          type: "doc",
          id: "api/read/get-parcel-snapshot-image",
          label: "Fetch a snapshot image (signed link)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/read/post-parcel-snapshots",
          label: "List a parcel's snapshots",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "admin",
      link: {
        type: "doc",
        id: "api/read/admin",
      },
      items: [
        {
          type: "doc",
          id: "api/read/post-admin-businesses-list",
          label: "Businesses List",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
